export const stateData = [
  { state: "Alabama", gov_name: "Kay Ivey", gov_email: "" },
  { state: "Alaska", gov_name: "", gov_email: "" },
  { state: "Arizona", gov_name: "Douglas Ducey", gov_email: "" },
  { state: "Arkansas", gov_name: "Asa Hutchinson", gov_email: "" },
  { state: "California", gov_name: "Gavin Newsom", gov_email: "" },
  { state: "Colorado", gov_name: "Jared Polis", gov_email: "" },
  { state: "Connecticut", gov_name: "Edward Lamont", gov_email: "" },
  { state: "Delaware", gov_name: "John Carney", gov_email: "" },
  { state: "Florida", gov_name: "Ronald DeSantis", gov_email: "" },
  { state: "Georgia", gov_name: "Nathan Deal", gov_email: "" },
  { state: "Hawaii", gov_name: "", gov_email: "" },
  { state: "Idaho", gov_name: "", gov_email: "" },
  { state: "Illinois", gov_name: "", gov_email: "" },
  { state: "Iowa", gov_name: "", gov_email: "" },
  { state: "Kansas", gov_name: "", gov_email: "" },
  { state: "Kentucky", gov_name: "", gov_email: "" },
  { state: "Lousiana", gov_name: "", gov_email: "" },
  { state: "Maine", gov_name: "", gov_email: "" },
  { state: "Maryland", gov_name: "", gov_email: "" },
  { state: "Massachusetts", gov_name: "", gov_email: "" },
  { state: "Michigan", gov_name: "", gov_email: "" },
  { state: "Minnesota", gov_name: "", gov_email: "" },
  { state: "Mississippi", gov_name: "", gov_email: "" },
  { state: "Missouri", gov_name: "", gov_email: "" },
  { state: "Montana", gov_name: "", gov_email: "" },
  { state: "Nevada", gov_name: "", gov_email: "" },
  { state: "New Hampshire", gov_name: "", gov_email: "" },
  { state: "New Jersey", gov_name: "", gov_email: "" },
  { state: "New Mexico", gov_name: "", gov_email: "" },
  { state: "New York", gov_name: "Andrew Cuomo", gov_email: "cuomo@govs" },
  { state: "North Carolina", gov_name: "", gov_email: "" },
  { state: "North Dakota", gov_name: "", gov_email: "" },
  { state: "Ohio", gov_name: "", gov_email: "" },
  { state: "Oklahoma", gov_name: "", gov_email: "" },
  { state: "Oregon", gov_name: "", gov_email: "" },
  { state: "Rhode Island", gov_name: "", gov_email: "" },
  { state: "South Carolina", gov_name: "", gov_email: "" },
  { state: "South Dakota", gov_name: "", gov_email: "" },
  { state: "Tennessee", gov_name: "", gov_email: "" },
  { state: "Texas", gov_name: "", gov_email: "" },
  { state: "Utah", gov_name: "", gov_email: "" },
  { state: "Vermont", gov_name: "", gov_email: "" },
  { state: "Virginia", gov_name: "", gov_email: "" },
  { state: "Washington", gov_name: "", gov_email: "" },
  { state: "West Virginia", gov_name: "", gov_email: "" },
  { state: "Wisconsin", gov_name: "", gov_email: "" },
  { state: "Wyoming", gov_name: "", gov_email: "" },
];
