export const stateData = [
  {
    state: "Alabama",
    gov_name: "Kay Ivey",
    gov_email: "Kay.Ivey@governor.alabama.gov",
    phone: "334-242-7900",
  },
  {
    state: "Alaska",
    gov_name: "Mike Dunleavy",
    gov_email: "governor@gov.state.ak.us",
    phone: "907-465-3500",
  },
  {
    state: "Arizona",
    gov_name: "Douglas Ducey",
    gov_email: "azgov@azgov.com",
    phone: "602-542-4331",
  },
  {
    state: "Arkansas",
    gov_name: "Asa Hutchinson",
    gov_email: "info@governor.arkansas.gov",
    phone: "501-682-2345",
  },
  {
    state: "California",
    gov_name: "Gavin Newsom",
    gov_email: "governor@governor.ca.gov",
    phone: "916-445-2841",
  },
  {
    state: "Colorado",
    gov_name: "Jared Polis",
    gov_email: "Governorpolis@state.co.us",
    phone: "303-866-2471",
  },
  {
    state: "Connecticut",
    gov_name: "Edward Lamont",
    gov_email: false,
    phone: "800-406-1527",
  },
  {
    state: "Delaware",
    gov_name: "John Carney",
    gov_email: "jcarney@state.de.us",
    phone: "302-577-4101",
  },
  {
    state: "Florida",
    gov_name: "Ronald DeSantis",
    gov_email: "governorron.desantis@eog.myflorida.com",
    phone: "850-488-7146",
  },
  {
    state: "Georgia",
    gov_name: "Nathan Deal",
    gov_email: "georgia.governor@gov.state.ga.us",
    phone: "404-656-1776",
  },
  {
    state: "Hawaii",
    gov_name: "David Ige",
    gov_email: "gov@gov.state.hi.us",
    phone: "808-586-0034",
  },
  {
    state: "Idaho",
    gov_name: "Brad Little",
    gov_email: "governor@gov.idaho.gov",
    phone: "208-334-2100",
  },
  {
    state: "Illinois",
    gov_name: "J.B. Pritzker",
    gov_email: "governor@state.il.us",
    phone: "217-782-0244",
  },
  {
    state: "Indiana",
    gov_name: "Eric Holcomb",
    gov_email: false,
    phone: "317-232-4567",
  },
  {
    state: "Iowa",
    gov_name: "Kimberly Reynolds",
    gov_email: false,
    phone: "515-281-5211",
  },
  {
    state: "Kansas",
    gov_name: "Laura Kelly",
    gov_email: false,
    phone: "785-296-3232",
  },
  {
    state: "Kentucky",
    gov_name: "Matthew Bevin",
    gov_email: "governor@mail.state.ky.us",
    phone: "502-564-2611",
  },
  {
    state: "Lousiana",
    gov_name: "John Edwards",
    gov_email: "jbe@la.gov",
    phone: "623-773-7328",
  },
  {
    state: "Maine",
    gov_name: "Janet Mills",
    gov_email: false,
    phone: "207-287-3531",
  },
  {
    state: "Maryland",
    gov_name: "Lawrence Hogan",
    gov_email: false,
    phone: "410-974-3901",
  },
  {
    state: "Massachusetts",
    gov_name: "Charles Baker",
    gov_email: "GOffice@state.ma.us",
    phone: "617-725-4005",
  },
  {
    state: "Michigan",
    gov_name: "Gretchen Whitmer",
    gov_email: "Gretchen.Whitmer@Michigan.gov",
    phone: "517-373-3400",
  },
  {
    state: "Minnesota",
    gov_name: "Tim Walz",
    gov_email: "tim.walz@state.mn.us",
    phone: "651-201-3400",
  },
  {
    state: "Mississippi",
    gov_name: "Dewey Bryant",
    gov_email: "governor@govreeves.ms.gov",
    phone: " 601-359-3150",
  },
  {
    state: "Missouri",
    gov_name: "Michael Parson",
    gov_email: "mogov@mail.mo.gov",
    phone: "573-751-3222",
  },
  {
    state: "Montana",
    gov_name: "Stephen Bullock",
    gov_email: false,
    phone: "406-444-3111",
  },
  {
    state: "Nebraska",
    gov_name: "John Ricketts",
    gov_email: "jodee@mail.state.ne.us",
    phone: "402-471-2244",
  },
  {
    state: "Nevada",
    gov_name: "Steve Sisolak",
    gov_email: "governor@govmail.state.nv.us",
    phone: "775-684-5670",
  },
  {
    state: "New Hampshire",
    gov_name: "Christopher Sununu",
    gov_email: false,
    phone: "603-271-2121",
  },
  {
    state: "New Jersey",
    gov_name: "Philip Murphy",
    gov_email: false,
    phone: "609-292-6000",
  },
  {
    state: "New Mexico",
    gov_name: "Michelle Lujan Grisham",
    gov_email: "gov@gov.state.nm.us",
    phone: "505-476-2200",
  },
  {
    state: "New York",
    gov_name: "Andrew Cuomo",
    gov_email: "cuomo@gov.cuomo@chamber.state.ny.us",
    phone: "518-474-8390",
  },
  {
    state: "North Carolina",
    gov_name: "Roy Cooper",
    gov_email: "gov.cuomo@chamber.state.ny.us",
    phone: "919-814-2000",
  },
  {
    state: "North Dakota",
    gov_name: "Douglas Burgum",
    gov_email: "governor@state.nd.us",
    phone: "701-328-2200",
  },
  {
    state: "Ohio",
    gov_name: "Michael DeWine",
    gov_email: false,
    phone: "614-466-3555",
  },
  {
    state: "Oklahoma",
    gov_name: "Kevin Stitt",
    gov_email: false,
    phone: "405-521-2342",
  },
  {
    state: "Oregon",
    gov_name: "Katherine Brown",
    gov_email: false,
    phone: "503-378-4582",
  },
  {
    state: "Pennsylvania",
    gov_name: "Thomas Wolf",
    gov_email: "governor@state.pa.us",
    phone: "717-787-2500",
  },
  {
    state: "Rhode Island",
    gov_name: "Gina Raimondo",
    gov_email: "rigov@gov.state.ri.us",
    phone: "401-222-2080",
  },
  {
    state: "South Carolina",
    gov_name: "Henry McMaster",
    gov_email: "governor@govoepp.state.sc.us",
    phone: "803-734-2100",
  },
  {
    state: "South Dakota",
    gov_name: "Kristi Noem",
    gov_email: "sdgov@gov.state.sd.us",
    phone: "605-773-3212",
  },
  {
    state: "Tennessee",
    gov_name: "Bill Lee",
    gov_email: "bill.lee@state.tn.us",
    phone: "615-741-2001",
  },
  {
    state: "Texas",
    gov_name: "Gregory Abbott",
    gov_email: "governor@state.tx.us",
    phone: "512-463-2000",
  },
  {
    state: "Utah",
    gov_name: "Gary Herbert",
    gov_email: "governor@utah.gov",
    phone: "801-538-1000",
  },
  {
    state: "Vermont",
    gov_name: "Philip Scott",
    gov_email: "pshumlin@state.vt.us",
    phone: "802-828-3333",
  },
  {
    state: "Virginia",
    gov_name: "Ralph Northam",
    gov_email: false,
    phone: "804-786-2211",
  },
  {
    state: "Washington",
    gov_name: "Jay Inslee",
    gov_email: "Governor.Gregoire@Governor.wa.gov",
    phone: "360-902-4111",
  },
  {
    state: "West Virginia",
    gov_name: "James Justice",
    gov_email: "governor@state.wv.us",
    phone: "304-558-2000",
  },
  {
    state: "Wisconsin",
    gov_name: "Tony Evers",
    gov_email: "wisgov@mail.state.wi.us",
    phone: "608-266-1212",
  },
  {
    state: "Wyoming",
    gov_name: "Mark Gordon",
    gov_email: "Governor@missc.state.wy.us",
    phone: "307-777-7434",
  },
];
